version: 0.0.2.{build}

before_build:
  - nuget restore
  - ps: |
      if($env:APPVEYOR_REPO_BRANCH -eq "master"){
        if($env:APPVEYOR_REPO_TAG){
          $env:CONFIGURATION = "Release"
          Write-Host "Switch to Release configuration"
        } else{
          $env:CONFIGURATION = "Debug"
          Write-Host "Switch to Debug configuration"
        }}

after_build:
  - cmd: if %APPVEYOR_REPO_BRANCH% == master "C:\projects\texteditor\packages\Tools.InnoSetup.5.5.6\tools\ISCC.exe" "C:\projects\texteditor\SetupScriptRelease.iss"

deploy: 
  - provider: GitHub
    tag: v$(APPVEYOR_BUILD_VERSION)
    release: TextEditor release of v$(APPVEYOR_BUILD_VERSION)
    description: New release of Text Editor
    auth_token: 2d1353e0da17919b1d828c4d880b6042540ac15d
    artifact: Setup
    draft: false
    prerelease: true
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: false      